<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Team_16">

<title>Mini Project Informs Data Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Mini_Project_Informs_Student-1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Mini_Project_Informs_Student-1_files/libs/quarto-html/quarto.js"></script>
<script src="Mini_Project_Informs_Student-1_files/libs/quarto-html/popper.min.js"></script>
<script src="Mini_Project_Informs_Student-1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Mini_Project_Informs_Student-1_files/libs/quarto-html/anchor.min.js"></script>
<link href="Mini_Project_Informs_Student-1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Mini_Project_Informs_Student-1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Mini_Project_Informs_Student-1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Mini_Project_Informs_Student-1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Mini_Project_Informs_Student-1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mini Project Informs Data Challenge</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Team_16 </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This project is based on the dataset provided for the <a href="https://connect.informs.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=cc03a951-a39a-467a-be4a-0189b203c4ca">INFORMS 2023 Data Challenge</a>. INFORMS teamed up with Blue Summit Supplies, an online retailer based in Alabama, to tackle real-world challenges in setting the right prices for their products. The eCommerce market is fast-paced, with prices changing constantly. Quick and smart pricing decisions are essential for staying competitive and profitable. The Informs data challenge aims to use the company’s actual sales data to explore how pricing impacts profits, with the goal of helping the company make better, faster pricing decisions. This projects takes a different route. As a team, your task is to understand the dataset and prepare it for further analyses.</p>
<ul>
<li><p><strong>Programming Language</strong>: R</p></li>
<li><p><strong>Deliverables</strong>: Quarto Document (.qmd) and HTML Knitted Document</p></li>
<li><p><strong>Libraries</strong>: Any libraries you deem necessary</p></li>
<li><p>There are 8 tasks, each is worth 12.5 points.</p></li>
</ul>
<section id="data-set-description" class="level4">
<h4 class="anchored" data-anchor-id="data-set-description">Data Set Description</h4>
<ul>
<li><p><code>sku</code>: This is the product ID, a unique identifier for each product.</p></li>
<li><p><code>salesdate</code>: This represents the date on which a particular product was sold.</p></li>
<li><p><code>price</code>: This is the price at which the product was sold on a given day.</p></li>
<li><p><code>unitsordered</code>: This variable shows the number of units of a product ordered on a particular day.</p></li>
<li><p><code>sales</code>: This represents the total revenue generated from the sale of a product on a given day (it is calculated as the product`s price times the number of units ordered).</p></li>
<li><p><code>cogs</code>: This stands for “Cost of Goods Sold”, which is the direct cost incurred by the company to produce or purchase the product.</p></li>
<li><p><code>fba</code>: This is the eCommerce fee associated with selling the product. It includes the costs of storage, packing, and shipping handled by Amazon.</p></li>
<li><p><code>reffee</code>: This is the eCommerce platform fee associated with selling the product (15% of sales).</p></li>
<li><p><code>adspend</code>: This represents the advertisement cost associated with the product.</p></li>
<li><p><code>profit</code>: This is the profit obtained from selling the product, calculated as sales minus the sum of cogs, fba, reffee, and adspend (profit = sales - cogs - fba - reffee - adspend).</p></li>
<li><p><code>comp_x_price</code>: This represents the price of a similar product sold by a competitor. Up to 5 competitors` price data are available for each product (67 items have O competitors, 65 items have 1 competitor, 56 items have 2 competitors, 28 items have 3 competitors, 9 items have 4 competitors, 2 items have 5 competitors).</p></li>
<li><p><code>comp_data_min_price</code>: This is the minimum price among all competitors for a similar product.</p></li>
<li><p><code>comp_data_max_price</code>: This is the maximum price among all competitors for a similar product.</p></li>
<li><p><code>managed_fba_stock_level</code>: This represents the available quantity of the product in stock.</p></li>
<li><p><code>min_price</code>: This is the minimum allowable selling price for the product</p></li>
<li><p><code>max_price</code>: This is the maximum allowable selling price for the product.</p></li>
</ul>
</section>
<section id="read-the-data-in-r" class="level4">
<h4 class="anchored" data-anchor-id="read-the-data-in-r">Read the data in R</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>informs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"2023 INFORMS BSS Data Challenge Dataset-1.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-1" class="level4">
<h4 class="anchored" data-anchor-id="task-1">TASK 1:</h4>
<p>In this task, you will be ensuring that all variables in the dataset <code>informs</code> are of the correct type. This is a crucial step in any data analysis project, as incorrect variable types can lead to misleading analyses and results.</p>
<section id="details" class="level5">
<h5 class="anchored" data-anchor-id="details">Details:</h5>
<ul>
<li><p>Declare categorical variables as factors.</p></li>
<li><p>Convert the date variable to a date format.</p></li>
<li><p>Ensure that numerical variables are set as numerical data types.</p></li>
<li><p>Your R object, <code>informs</code> , should have <code>122801</code> rows and <code>20</code> columns.</p></li>
<li><p>Print the data structure below with <code>str(informs)</code> function.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert categorical variables to factors</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sku"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>informs[categorical_vars] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(informs[categorical_vars], as.factor)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the 'salesdate' variable to a date format</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>salesdate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(informs<span class="sc">$</span>salesdate)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure that numerical variables are set as numerical data types</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>numerical_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"price"</span>, <span class="st">"unitsordered"</span>, <span class="st">"sales"</span>, <span class="st">"cogs"</span>, <span class="st">"fba"</span>, <span class="st">"reffee"</span>, <span class="st">"adspend"</span>, </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"profit"</span>, <span class="st">"comp_data_min_price"</span>, <span class="st">"comp_data_max_price"</span>, <span class="st">"managed_fba_stock_level"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"min_price"</span>, <span class="st">"max_price"</span>, <span class="st">"comp_1_price"</span>, <span class="st">"comp_2_price"</span>, <span class="st">"comp_3_price"</span>, <span class="st">"comp_4_price"</span>, </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"comp_5_price"</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>informs[numerical_vars] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(informs[numerical_vars], as.numeric)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure of the 'informs' dataset</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   122801 obs. of  20 variables:
 $ sku                    : Factor w/ 227 levels "Binder Dividers SKU 1",..: 61 61 61 61 61 61 61 61 61 61 ...
 $ salesdate              : Date, format: "2022-01-01" "2022-01-02" ...
 $ price                  : num  29.5 30 29.7 29.8 29.8 ...
 $ unitsordered           : num  19 13 84 78 83 61 66 18 20 70 ...
 $ sales                  : num  560 390 2494 2324 2473 ...
 $ cogs                   : num  236 161 1042 968 1030 ...
 $ fba                    : num  156 107 690 641 682 501 543 148 164 575 ...
 $ reffee                 : num  84 58 374 349 371 273 290 81 90 314 ...
 $ adspend                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ profit                 : num  84 64 388 366 390 292 281 88 98 334 ...
 $ comp_1_price           : num  28.5 28.5 28.5 28.5 28.5 ...
 $ comp_2_price           : num  28 28 28 28 28 ...
 $ comp_3_price           : num  31 31 31 31 31 ...
 $ comp_4_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_5_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_data_min_price    : num  28 28 28 28 28 ...
 $ comp_data_max_price    : num  31 31 31 31 31 ...
 $ managed_fba_stock_level: num  NA NA NA NA NA NA NA NA NA NA ...
 $ min_price              : num  28 28 28 28 28 ...
 $ max_price              : num  35 35 35 35 35 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="task-2" class="level4">
<h4 class="anchored" data-anchor-id="task-2">TASK 2:</h4>
<p>In this task, you are required to calculate the percentage of missing values for each variable in the <code>informs</code> dataset and display the results in a table. Understanding the extent of missing data is a crucial step in data analysis, as it can significantly impact the results.</p>
<section id="details-1" class="level5">
<h5 class="anchored" data-anchor-id="details-1">Details:</h5>
<ul>
<li>Your printed table should display the variable name, <code>variable</code> in the first column and the percentage of missing values, called <code>Percent_Missing</code>, in the second column.</li>
<li>The table should be sorted in descending order based on the percentage of missingness (<code>Percent_Missing</code>). If two variables have the same percentage of missingness, then they should be sorted by their variable names (<code>variable</code>) in ascending alphabetical order.</li>
<li>Your code should print the table below</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the percentage of missing values for each variable</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>missing_percentage <span class="ot">&lt;-</span> informs <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.)) <span class="sc">/</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"Percent_Missing"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Percent_Missing), variable)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the table</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_percentage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   variable                Percent_Missing
   &lt;chr&gt;                             &lt;dbl&gt;
 1 comp_5_price                      0.986
 2 comp_4_price                      0.941
 3 comp_3_price                      0.831
 4 comp_2_price                      0.605
 5 comp_1_price                      0.359
 6 comp_data_max_price               0.306
 7 comp_data_min_price               0.306
 8 managed_fba_stock_level           0.197
 9 adspend                           0    
10 cogs                              0    
11 fba                               0    
12 max_price                         0    
13 min_price                         0    
14 price                             0    
15 profit                            0    
16 reffee                            0    
17 sales                             0    
18 salesdate                         0    
19 sku                               0    
20 unitsordered                      0    </code></pre>
</div>
</div>
</section>
</section>
<section id="task-3" class="level4">
<h4 class="anchored" data-anchor-id="task-3">TASK 3:</h4>
<p>In this task, you are required to create a new column in the <strong><code>informs</code></strong> dataset called <strong><code>number_competitors</code></strong>. This column should contain the total number of competitors. In other words, it contains the total number of non-missing values for the competitor price variables: <strong><code>comp_1_price</code></strong>, <strong><code>comp_2_price</code></strong>, <strong><code>comp_3_price</code></strong>, <strong><code>comp_4_price</code></strong>, and <strong><code>comp_5_price</code></strong>.</p>
<section id="details-2" class="level5">
<h5 class="anchored" data-anchor-id="details-2">Details:</h5>
<ul>
<li><p>The <strong><code>number_competitors</code></strong> column will have a value of <code>0</code> if there are no competitor data available for that particular row.</p></li>
<li><p>If data from only three competitors is present in a given row, then <strong><code>number_competitors</code></strong> will have a value of 3.</p></li>
<li><p>After completing this task, your <strong><code>informs</code></strong> data frame should consist of 122,801 rows and 21 columns</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary library </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the 'number_competitors' column</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>informs <span class="ot">&lt;-</span> informs <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">number_competitors =</span> <span class="fu">rowSums</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">select</span>(., <span class="fu">starts_with</span>(<span class="st">"comp_"</span>)))))</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure of the updated 'informs' dataset</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   122801 obs. of  21 variables:
 $ sku                    : Factor w/ 227 levels "Binder Dividers SKU 1",..: 61 61 61 61 61 61 61 61 61 61 ...
 $ salesdate              : Date, format: "2022-01-01" "2022-01-02" ...
 $ price                  : num  29.5 30 29.7 29.8 29.8 ...
 $ unitsordered           : num  19 13 84 78 83 61 66 18 20 70 ...
 $ sales                  : num  560 390 2494 2324 2473 ...
 $ cogs                   : num  236 161 1042 968 1030 ...
 $ fba                    : num  156 107 690 641 682 501 543 148 164 575 ...
 $ reffee                 : num  84 58 374 349 371 273 290 81 90 314 ...
 $ adspend                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ profit                 : num  84 64 388 366 390 292 281 88 98 334 ...
 $ comp_1_price           : num  28.5 28.5 28.5 28.5 28.5 ...
 $ comp_2_price           : num  28 28 28 28 28 ...
 $ comp_3_price           : num  31 31 31 31 31 ...
 $ comp_4_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_5_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_data_min_price    : num  28 28 28 28 28 ...
 $ comp_data_max_price    : num  31 31 31 31 31 ...
 $ managed_fba_stock_level: num  NA NA NA NA NA NA NA NA NA NA ...
 $ min_price              : num  28 28 28 28 28 ...
 $ max_price              : num  35 35 35 35 35 ...
 $ number_competitors     : num  5 5 5 5 5 5 5 5 5 5 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="task-4" class="level4">
<h4 class="anchored" data-anchor-id="task-4">TASK 4:</h4>
<ul>
<li><p>In this task, you are required to create two new columns in the informs dataset called <strong><code>median_competitor_price</code></strong> and <strong><code>price_differences</code></strong>.</p></li>
<li><p>This first column,<strong><code>median_competitor_price</code></strong> , should contain the median price among competitors. In other words, it contains the median of non-missing values for the competitor price variables: <strong><code>comp_1_price</code></strong>, <strong><code>comp_2_price</code></strong>, <strong><code>comp_3_price</code></strong>, <strong><code>comp_4_price</code></strong>, and <strong><code>comp_5_price</code></strong>. The <strong><code>median_competitor_price</code></strong> column will have a value of <strong><code>NA</code></strong> if there are no competitor data available for that particular row.</p></li>
<li><p>The second column, <strong><code>price_differences</code></strong> should represent the difference between the company’s price (<code>price</code>) and the median competitor price, <strong><code>median_competitor_price</code></strong> , for each transaction (row). If there are no competitor data available for that particular row, set <strong><code>price_differences</code></strong> to <code>NA</code>.</p></li>
<li><p>After completing this task, your informs data frame should consist of 122,801 rows and 23 columns.<br>
</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary library </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the median competitor price for each row</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>informs <span class="ot">&lt;-</span> informs <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">median_competitor_price =</span> <span class="fu">apply</span>(<span class="fu">select</span>(., <span class="fu">starts_with</span>(<span class="st">"comp_"</span>)), <span class="dv">1</span>, <span class="cf">function</span>(x) {</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    non_na_values <span class="ot">&lt;-</span> x[<span class="sc">!</span><span class="fu">is.na</span>(x)]</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(non_na_values) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="cn">NA</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">median</span>(non_na_values))</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  }))</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the price differences</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>informs <span class="ot">&lt;-</span> informs <span class="sc">%&gt;%</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price_differences =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(median_competitor_price), <span class="cn">NA</span>, price <span class="sc">-</span> median_competitor_price))</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure of the updated 'informs' dataset</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   122801 obs. of  23 variables:
 $ sku                    : Factor w/ 227 levels "Binder Dividers SKU 1",..: 61 61 61 61 61 61 61 61 61 61 ...
 $ salesdate              : Date, format: "2022-01-01" "2022-01-02" ...
 $ price                  : num  29.5 30 29.7 29.8 29.8 ...
 $ unitsordered           : num  19 13 84 78 83 61 66 18 20 70 ...
 $ sales                  : num  560 390 2494 2324 2473 ...
 $ cogs                   : num  236 161 1042 968 1030 ...
 $ fba                    : num  156 107 690 641 682 501 543 148 164 575 ...
 $ reffee                 : num  84 58 374 349 371 273 290 81 90 314 ...
 $ adspend                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ profit                 : num  84 64 388 366 390 292 281 88 98 334 ...
 $ comp_1_price           : num  28.5 28.5 28.5 28.5 28.5 ...
 $ comp_2_price           : num  28 28 28 28 28 ...
 $ comp_3_price           : num  31 31 31 31 31 ...
 $ comp_4_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_5_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_data_min_price    : num  28 28 28 28 28 ...
 $ comp_data_max_price    : num  31 31 31 31 31 ...
 $ managed_fba_stock_level: num  NA NA NA NA NA NA NA NA NA NA ...
 $ min_price              : num  28 28 28 28 28 ...
 $ max_price              : num  35 35 35 35 35 ...
 $ number_competitors     : num  5 5 5 5 5 5 5 5 5 5 ...
 $ median_competitor_price: num  28.5 28.5 28.5 28.5 28.5 ...
 $ price_differences      : num  1 1.5 1.2 1.3 1.3 ...</code></pre>
</div>
</div>
</section>
<section id="task-5" class="level4">
<h4 class="anchored" data-anchor-id="task-5">TASK 5:</h4>
<p>In this task, your goal is to create an R object called <strong><code>average_profit_vs_competitors</code></strong> that will store the <code>sku</code> and the following two variables:</p>
<ol type="1">
<li><p>The average profit per unit for each <code>sku</code>, called <code>average_profit</code> . The <code>average_profit</code>should be calculated as <span class="math inline">\(\frac{profit}{unitsordered}\)</span>​.</p></li>
<li><p>The average number of competitors per <code>sku</code>, called <code>average_number_competitors.</code> The <code>average_number_competitors</code> for each <code>sku</code> should be calculated as <code>mean(number_competitors)</code> in R.</p></li>
</ol>
<section id="details-3" class="level5">
<h5 class="anchored" data-anchor-id="details-3"><strong>Details:</strong></h5>
<ul>
<li><p>Compute the average profit for each <code>sku</code>, labeling this new variable as <strong><code>average_profit</code></strong>.</p></li>
<li><p>Double check your calculations to make sure you do not have <strong><code>-Inf</code></strong> for <strong><code>average_profit</code></strong> values. The issue of <strong><code>-Inf</code></strong> most likely arises when <strong><code>unitsordered</code></strong> is zero, as division by zero in R returns <strong><code>-Inf</code></strong>. If <strong><code>unitsordered</code></strong> is zero for a given day and <code>sku</code>, you can temporarily set it to <strong><code>NA</code></strong> to avoid <strong><code>-Inf</code></strong> in <strong><code>average_profit</code></strong> calculations.</p></li>
<li><p>Arrange these calculated average profits in descending order for easier interpretation.</p></li>
<li><p>After completing this task, your R object named <strong><code>average_profit_vs_competitors</code></strong> should have exactly 227 rows and 3 columns: <code>sku</code>, <code>average_profit</code>, and <code>average_number_competitors</code></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary library</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average profit per unit for each SKU and the average number of competitors</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>average_profit_vs_competitors <span class="ot">&lt;-</span> informs <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Temporarily set unitsordered to NA when it's zero to avoid -Inf in average_profit</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">unitsordered =</span> <span class="fu">ifelse</span>(unitsordered <span class="sc">==</span> <span class="dv">0</span>, <span class="cn">NA</span>, unitsordered)) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sku) <span class="sc">%&gt;%</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">average_profit =</span> <span class="fu">sum</span>(profit, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sum</span>(unitsordered, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">average_number_competitors =</span> <span class="fu">mean</span>(number_competitors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Arrange in descending order of average_profit</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(average_profit))</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure of the 'average_profit_vs_competitors' object</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(average_profit_vs_competitors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [227 × 3] (S3: tbl_df/tbl/data.frame)
 $ sku                       : Factor w/ 227 levels "Binder Dividers SKU 1",..: 212 23 24 213 226 26 185 206 103 197 ...
 $ average_profit            : num [1:227] 19.4 17.3 15.3 15.2 14.3 ...
 $ average_number_competitors: num [1:227] 2.92 0 0 4 2.64 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="task-6" class="level4">
<h4 class="anchored" data-anchor-id="task-6">TASK 6:</h4>
<p>In this task, you are required to create a scatter plot using the <strong><code>average_profit_vs_competitors</code></strong> dataset and interpret it. Your plot should display the relationship between <strong><code>average_profit</code></strong> and <strong><code>average_number_competitors</code></strong>, specifically for rows where <strong><code>average_profit</code></strong> is greater than zero. Additionally, include a linear regression line on the scatter plot to gauge the overall trend.</p>
<section id="details-4" class="level5">
<h5 class="anchored" data-anchor-id="details-4">Details:</h5>
<ul>
<li><p>Generate a scatter plot to display <strong><code>average_profit</code></strong> on the y-axis and <strong><code>average_number_competitors</code></strong> on the x-axis.</p></li>
<li><p>Overlay a linear regression line on the scatter plot.</p></li>
<li><p>Filter the data to include only rows where <strong><code>average_profit</code></strong> is greater than zero.</p></li>
<li><p>Label your axis</p></li>
<li><p>Interpret your findings in one short paragraph.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data to include only rows where average_profit is greater than zero</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> average_profit_vs_competitors <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(average_profit <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatter plot with a linear regression line</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>scatter_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(filtered_data, <span class="fu">aes</span>(<span class="at">x =</span> average_number_competitors, <span class="at">y =</span> average_profit)) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>           <span class="co"># Add scatter points</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span>  <span class="co"># Add linear regression line</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average Number of Competitors"</span>, <span class="at">y =</span> <span class="st">"Average Profit per Unit"</span>) <span class="sc">+</span>  <span class="co"># Label axes</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Scatter Plot of Average Profit vs. Average Number of Competitors"</span>)  <span class="co"># Add title</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the scatter plot</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scatter_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Mini_Project_Informs_Student-1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpretation-of-the-scatter-plot" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-of-the-scatter-plot">Interpretation of the Scatter Plot</h5>
<p>The scatter plot indicates that the average number of rivals and the average profit per unit have a moderately negative connection. The average profit per unit tends to decline as the average number of competitors rises, suggesting that greater competition may result in lesser profitability.</p>
</section>
</section>
<section id="task-7" class="level4">
<h4 class="anchored" data-anchor-id="task-7">TASK 7:</h4>
<ul>
<li><p>The total sales revenue of a firm is calculated as the product of the price per unit and the total quantity sold. The impact of a price increase on total sales depends on the corresponding decrease in the quantity sold. In a highly competitive market, even a small increase in price can lead to a significant drop in sales, which in turn can reduce both total sales and profits.</p>
<p>For this task, please complete the following steps:</p>
<ol type="1">
<li><p>Create a subset of the <strong><code>informs</code></strong> dataset by removing rows that have no competitors. Name this new dataset <strong><code>informs_reduced</code></strong>.</p></li>
<li><p>Calculate the correlation between <strong><code>price</code></strong> and <strong><code>profit</code></strong> for cases where <strong><code>price_differences &gt; 0</code></strong> and <strong><code>price_differences &lt;= 0</code></strong>. Print and interpret your findings.</p></li>
<li><p>Calculate the correlation between <strong><code>price</code></strong> and <strong><code>units_ordered</code></strong> for cases where <strong><code>price_differences &gt; 0</code></strong> and <strong><code>price_differences &lt;= 0</code></strong>. Print and interpret your findings.</p></li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a subset of 'informs' dataset by removing rows with no competitors</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>informs_reduced <span class="ot">&lt;-</span> informs <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(number_competitors <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between 'price' and 'profit' for price_differences &gt; 0</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>correlation_profit_positive <span class="ot">&lt;-</span> <span class="fu">cor</span>(informs_reduced<span class="sc">$</span>price[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&gt;</span> <span class="dv">0</span>],</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                                   informs_reduced<span class="sc">$</span>profit[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between 'price' and 'profit' for price_differences &lt;= 0</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>correlation_profit_negative <span class="ot">&lt;-</span> <span class="fu">cor</span>(informs_reduced<span class="sc">$</span>price[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&lt;=</span> <span class="dv">0</span>],</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                                   informs_reduced<span class="sc">$</span>profit[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&lt;=</span> <span class="dv">0</span>])</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between 'price' and 'unitsordered' for price_differences &gt; 0</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>correlation_units_ordered_positive <span class="ot">&lt;-</span> <span class="fu">cor</span>(informs_reduced<span class="sc">$</span>price[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&gt;</span> <span class="dv">0</span>],</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                                          informs_reduced<span class="sc">$</span>unitsordered[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between 'price' and 'unitsordered' for price_differences &lt;= 0</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>correlation_units_ordered_negative <span class="ot">&lt;-</span> <span class="fu">cor</span>(informs_reduced<span class="sc">$</span>price[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&lt;=</span> <span class="dv">0</span>],</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>                                          informs_reduced<span class="sc">$</span>unitsordered[informs_reduced<span class="sc">$</span>price_differences <span class="sc">&lt;=</span> <span class="dv">0</span>])</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the findings</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Correlation between price and profit (price_differences &gt; 0):"</span>, correlation_profit_positive, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation between price and profit (price_differences &gt; 0): 0.2473491 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Correlation between price and profit (price_differences &lt;= 0):"</span>, correlation_profit_negative, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation between price and profit (price_differences &lt;= 0): 0.3082064 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Correlation between price and unitsordered (price_differences &gt; 0):"</span>, correlation_units_ordered_positive, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation between price and unitsordered (price_differences &gt; 0): -0.02049753 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Correlation between price and unitsordered (price_differences &lt;= 0):"</span>, correlation_units_ordered_negative, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation between price and unitsordered (price_differences &lt;= 0): 0.236388 </code></pre>
</div>
</div>
<section id="interpretation-of-the-findings" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-of-the-findings">Interpretation of the findings</h5>
<p>Correlation between price and profit (price_differences &gt; 0):</p>
<p>Positive correlation (0.25): Higher prices in competitive markets tend to lead to higher profits, but the relationship is not very strong. Correlation between price and profit (price_differences &lt;= 0):</p>
<p>Positive correlation (0.31): Maintaining lower prices or facing less competition is associated with higher profits, with a slightly stronger relationship. Correlation between price and unitsordered (price_differences &gt; 0):</p>
<p>Weak negative correlation (-0.02): Increasing prices in competitive markets has a minimal impact on the quantity of units ordered. Correlation between price and unitsordered (price_differences &lt;= 0):</p>
<p>Positive correlation (0.24): Lower prices or reduced competition tend to result in higher quantities ordered, but the effect is not very strong. These findings suggest that price changes in different competitive scenarios have varying effects on profits and customer demand, with moderate to weak relationships observed.</p>
</section>
</section>
<section id="task-8" class="level4">
<h4 class="anchored" data-anchor-id="task-8">TASK 8:</h4>
<p>Based on your insights from Task 7, earlier tasks, or your own analyses, provide a pricing recommendation to help the company’s to increase their profitability. Keep your response concise. You may include a graph or analysis to substantiate your recommendation. Summarize your suggestion and rationale in a brief paragraph.</p>
<section id="pricing-recommendation" class="level5">
<h5 class="anchored" data-anchor-id="pricing-recommendation">Pricing Recommendation</h5>
<p>Consider boosting prices in markets that are highly competitive (price_differences &gt; 0) and keeping prices competitive in markets that are less competitive (price_differences = 0) in order to increase profitability. This tactic tries to maximize earnings while skillfully regulating client demand, and it is consistent with the patterns that have been noticed.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>